### ISSUE TITLE
R package maintainer email address is dead, package scheduled for archival

### ISSUE THREAD

**Issue by dfsp-spirit** [aroneklund/squash#1]
Dear Aron,

I just wanted to let you know that I received an email from CRAN today (because one of my packages uses *squash*) that says:

> We have repeatedly asked for an update fixing the check problems shown
> on
> <https://cran.r-project.org/web/checks/check_results_squash.html>
> with no reply from the maintainer thus far.
> 
> Thus, package squash is now scheduled for archival on 2020-03-04, and
> archiving this will necessitate also archiving its strong reverse
> dependencies.

I noticed that your maintainer email address given in the package description is dead, so I thought you may not be aware of this and wanted to let you know.

If you are still maintaining the package, please contact CRAN@R-project.org

**Comment by aroneklund** [comment]
Thanks for letting me know!  I will fix this.

**Comment by aroneklund** [comment]
I fixed the check problems, updated my email address, and submitted the updated package to CRAN, with a note pleading to not archive the package.  I hope this works!

**Comment by dfsp-spirit** [comment]
Thanks Aron, that's great news.
